In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import re
import seaborn as sns

C:\Users\iayav\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.1
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [2]:
df = pd.read_csv('Capstone_project_step3_Ahmet')
df.T

,0,1,2,3,4,5,6,7,8,9,...,14355,14356,14357,14358,14359,14360,14361,14362,14363,14364
make_model,Audi A1,Audi A1,Audi A1,Audi A1,Audi A1,Audi A1,Audi A1,Audi A1,Audi A1,Audi A1,...,Renault Espace,Renault Espace,Renault Espace,Renault Espace,Renault Espace,Renault Espace,Renault Espace,Renault Espace,Renault Espace,Renault Espace
body_type,Sedans,Sedans,Sedans,Sedans,Sedans,Sedans,Station wagon,Compact,Sedans,Sedans,...,Van,Van,Sedans,Station wagon,Van,Van,Van,Van,Van,Van
price,15770,14500,14640,14500,16790,15090,16422,14480,16700,17990,...,41395,41400,41043,41390,39990,39980,39950,39950,39875,39700
vat,VAT deductible,Price negotiable,VAT deductible,VAT deductible,VAT deductible,VAT deductible,VAT deductible,VAT deductible,VAT deductible,VAT deductible,...,VAT deductible,VAT deductible,VAT deductible,VAT deductible,VAT deductible,VAT deductible,VAT deductible,VAT deductible,VAT deductible,VAT deductible
km,56013.0,80000.0,83450.0,73000.0,16200.0,63668.0,62111.0,14986.0,57000.0,16103.0,...,5000.0,10.0,34130.127828,50.0,3500.0,100.0,34130.127828,34130.127828,15.0,10.0
prev_owner,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
hp,66.0,141.0,85.0,66.0,66.0,85.0,85.0,66.0,85.0,70.0,...,147.0,118.0,147.0,118.0,147.0,118.0,147.0,147.0,146.0,147.0
type,Used,Used,Used,Used,Used,Used,Used,Used,Used,Used,...,Demonstration,Pre-registered,New,Pre-registered,Demonstration,Pre-registered,New,New,Pre-registered,Pre-registered
first_registration,2016.0,2017.0,2016.0,2016.0,2016.0,2016.0,2016.0,2016.0,2016.0,2017.0,...,2019.0,2019.0,2019.0,2019.0,2019.0,2019.0,2019.0,2019.0,2019.0,2019.0
body_color,Black,Red,Black,Brown,Black,White,White,Red,Grey,White,...,Grey,Grey,Black,Grey,Black,White,Black,Grey,White,Grey
nr_of_doors,5.0,3.0,4.0,3.0,5.0,4.0,4.0,5.0,5.0,5.0,...,5.0,5.0,4.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0
nr_of_seats,5.0,4.0,4.0,4.0,5.0,5.0,5.0,5.0,4.0,4.0,...,7.0,7.0,5.0,7.0,5.0,7.0,5.0,5.0,7.0,7.0
gearing_type,Automatic,Automatic,Automatic,Automatic,Automatic,Automatic,Automatic,Automatic,Automatic,Automatic,...,Automatic,Automatic,Automatic,Automatic,Automatic,Automatic,Automatic,Automatic,Automatic,Automatic
displacement,1422.0,1798.0,1598.0,1422.0,1422.0,1598.0,1598.0,1422.0,1598.0,999.0,...,1997.0,1997.0,1997.0,1997.0,1997.0,1598.0,1997.0,1997.0,1997.0,1997.0
cylinders,3.0,4.0,4.0,3.0,3.0,3.0,4.0,4.0,4.0,4.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0
fuel,Diesel,Benzine,Diesel,Diesel,Diesel,Diesel,Diesel,Diesel,Diesel,Benzine,...,Diesel,Diesel,Diesel,Diesel,Diesel,Diesel,Diesel,Diesel,Diesel,Diesel
co_2_emission,992.0,1292.0,992.0,992.0,1092.0,922.0,982.0,972.0,972.0,1239.396722,...,1392.0,1352.0,1392.0,1352.0,1239.396722,1232.0,1392.0,1392.0,1392.0,1392.0
emission_class,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,...,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0
extras,Alloy wheels,Alloy wheels,Alloy wheels,Alloy wheels,Alloy wheels,Alloy wheels,Alloy wheels,Alloy wheels,Alloy wheels,Alloy wheels,...,Alloy wheels,Alloy wheels,Alloy wheels,Alloy wheels,Alloy wheels,Alloy wheels,Alloy wheels,Alloy wheels,Alloy wheels,Alloy wheels
gears,7.0,7.0,6.0,6.0,7.0,7.0,7.0,7.0,7.0,7.0,...,6.0,6.0,6.0,6.0,7.0,6.0,6.0,6.0,6.0,6.0
cons_comb,3.8,5.6,3.8,3.8,4.1,3.5,3.7,3.7,3.7,4.895549,...,5.3,5.1,5.3,5.3,4.895549,4.7,5.3,5.3,5.3,5.3
cons_city,4.3,7.1,4.4,4.3,4.6,4.3,4.3,4.2,4.3,5.947801,...,6.2,5.7,6.2,6.0,5.947801,5.1,6.2,6.2,6.2,6.2
cons_country,3.5,4.7,3.4,3.5,3.8,3.1,3.4,3.4,3.4,4.238404,...,4.7,4.8,4.7,5.0,4.238404,4.4,4.7,4.7,4.7,4.7

Let's obtain the dummies.

### Make & Model

In [3]:
one_hot = pd.get_dummies(df, columns = ['make_model'])
df = one_hot
df

,body_type,price,vat,km,prev_owner,hp,type,first_registration,body_color,nr_of_doors,...,cons_country,make_model_Audi A1,make_model_Audi A2,make_model_Audi A3,make_model_Opel Astra,make_model_Opel Corsa,make_model_Opel Insignia,make_model_Renault Clio,make_model_Renault Duster,make_model_Renault Espace
0,Sedans,15770,VAT deductible,56013.000000,2.0,66.0,Used,2016.0,Black,5.0,...,3.5,1,0,0,0,0,0,0,0,0
1,Sedans,14500,Price negotiable,80000.000000,1.0,141.0,Used,2017.0,Red,3.0,...,4.7,1,0,0,0,0,0,0,0,0
2,Sedans,14640,VAT deductible,83450.000000,1.0,85.0,Used,2016.0,Black,4.0,...,3.4,1,0,0,0,0,0,0,0,0
3,Sedans,14500,VAT deductible,73000.000000,1.0,66.0,Used,2016.0,Brown,3.0,...,3.5,1,0,0,0,0,0,0,0,0
4,Sedans,16790,VAT deductible,16200.000000,1.0,66.0,Used,2016.0,Black,5.0,...,3.8,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14360,Van,39980,VAT deductible,100.000000,1.0,118.0,Pre-registered,2019.0,White,5.0,...,4.4,0,0,0,0,0,0,0,0,1
14361,Van,39950,VAT deductible,34130.127828,1.0,147.0,New,2019.0,Black,5.0,...,4.7,0,0,0,0,0,0,0,0,1
14362,Van,39950,VAT deductible,34130.127828,1.0,147.0,New,2019.0,Grey,5.0,...,4.7,0,0,0,0,0,0,0,0,1
14363,Van,39875,VAT deductible,15.000000,1.0,146.0,Pre-registered,2019.0,White,5.0,...,4.7,0,0,0,0,0,0,0,0,1
14364,Van,39700,VAT deductible,10.000000,1.0,147.0,Pre-registered,2019.0,Grey,5.0,...,4.7,0,0,0,0,0,0,0,0,1

### Body Type

In [4]:
one_hot = pd.get_dummies(df, columns = ['body_type'])
df = one_hot
df

,price,vat,km,prev_owner,hp,type,first_registration,body_color,nr_of_doors,nr_of_seats,...,make_model_Renault Espace,body_type_Compact,body_type_Convertible,body_type_Coupe,body_type_Off-Road,body_type_Other,body_type_Sedans,body_type_Station wagon,body_type_Transporter,body_type_Van
0,15770,VAT deductible,56013.000000,2.0,66.0,Used,2016.0,Black,5.0,5.0,...,0,0,0,0,0,0,1,0,0,0
1,14500,Price negotiable,80000.000000,1.0,141.0,Used,2017.0,Red,3.0,4.0,...,0,0,0,0,0,0,1,0,0,0
2,14640,VAT deductible,83450.000000,1.0,85.0,Used,2016.0,Black,4.0,4.0,...,0,0,0,0,0,0,1,0,0,0
3,14500,VAT deductible,73000.000000,1.0,66.0,Used,2016.0,Brown,3.0,4.0,...,0,0,0,0,0,0,1,0,0,0
4,16790,VAT deductible,16200.000000,1.0,66.0,Used,2016.0,Black,5.0,5.0,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14360,39980,VAT deductible,100.000000,1.0,118.0,Pre-registered,2019.0,White,5.0,7.0,...,1,0,0,0,0,0,0,0,0,1
14361,39950,VAT deductible,34130.127828,1.0,147.0,New,2019.0,Black,5.0,5.0,...,1,0,0,0,0,0,0,0,0,1
14362,39950,VAT deductible,34130.127828,1.0,147.0,New,2019.0,Grey,5.0,5.0,...,1,0,0,0,0,0,0,0,0,1
14363,39875,VAT deductible,15.000000,1.0,146.0,Pre-registered,2019.0,White,5.0,7.0,...,1,0,0,0,0,0,0,0,0,1
14364,39700,VAT deductible,10.000000,1.0,147.0,Pre-registered,2019.0,Grey,5.0,7.0,...,1,0,0,0,0,0,0,0,0,1

### VAT

In [5]:
one_hot = pd.get_dummies(df, columns = ['vat'])
df = one_hot
df

,price,km,prev_owner,hp,type,first_registration,body_color,nr_of_doors,nr_of_seats,gearing_type,...,body_type_Convertible,body_type_Coupe,body_type_Off-Road,body_type_Other,body_type_Sedans,body_type_Station wagon,body_type_Transporter,body_type_Van,vat_Price negotiable,vat_VAT deductible
0,15770,56013.000000,2.0,66.0,Used,2016.0,Black,5.0,5.0,Automatic,...,0,0,0,0,1,0,0,0,0,1
1,14500,80000.000000,1.0,141.0,Used,2017.0,Red,3.0,4.0,Automatic,...,0,0,0,0,1,0,0,0,1,0
2,14640,83450.000000,1.0,85.0,Used,2016.0,Black,4.0,4.0,Automatic,...,0,0,0,0,1,0,0,0,0,1
3,14500,73000.000000,1.0,66.0,Used,2016.0,Brown,3.0,4.0,Automatic,...,0,0,0,0,1,0,0,0,0,1
4,16790,16200.000000,1.0,66.0,Used,2016.0,Black,5.0,5.0,Automatic,...,0,0,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14360,39980,100.000000,1.0,118.0,Pre-registered,2019.0,White,5.0,7.0,Automatic,...,0,0,0,0,0,0,0,1,0,1
14361,39950,34130.127828,1.0,147.0,New,2019.0,Black,5.0,5.0,Automatic,...,0,0,0,0,0,0,0,1,0,1
14362,39950,34130.127828,1.0,147.0,New,2019.0,Grey,5.0,5.0,Automatic,...,0,0,0,0,0,0,0,1,0,1
14363,39875,15.000000,1.0,146.0,Pre-registered,2019.0,White,5.0,7.0,Automatic,...,0,0,0,0,0,0,0,1,0,1
14364,39700,10.000000,1.0,147.0,Pre-registered,2019.0,Grey,5.0,7.0,Automatic,...,0,0,0,0,0,0,0,1,0,1

### Type

In [6]:
one_hot = pd.get_dummies(df, columns = ['type'])
df = one_hot
df

,price,km,prev_owner,hp,first_registration,body_color,nr_of_doors,nr_of_seats,gearing_type,displacement,...,body_type_Station wagon,body_type_Transporter,body_type_Van,vat_Price negotiable,vat_VAT deductible,type_Demonstration,type_Employee's car,type_New,type_Pre-registered,type_Used
0,15770,56013.000000,2.0,66.0,2016.0,Black,5.0,5.0,Automatic,1422.0,...,0,0,0,0,1,0,0,0,0,1
1,14500,80000.000000,1.0,141.0,2017.0,Red,3.0,4.0,Automatic,1798.0,...,0,0,0,1,0,0,0,0,0,1
2,14640,83450.000000,1.0,85.0,2016.0,Black,4.0,4.0,Automatic,1598.0,...,0,0,0,0,1,0,0,0,0,1
3,14500,73000.000000,1.0,66.0,2016.0,Brown,3.0,4.0,Automatic,1422.0,...,0,0,0,0,1,0,0,0,0,1
4,16790,16200.000000,1.0,66.0,2016.0,Black,5.0,5.0,Automatic,1422.0,...,0,0,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14360,39980,100.000000,1.0,118.0,2019.0,White,5.0,7.0,Automatic,1598.0,...,0,0,1,0,1,0,0,0,1,0
14361,39950,34130.127828,1.0,147.0,2019.0,Black,5.0,5.0,Automatic,1997.0,...,0,0,1,0,1,0,0,1,0,0
14362,39950,34130.127828,1.0,147.0,2019.0,Grey,5.0,5.0,Automatic,1997.0,...,0,0,1,0,1,0,0,1,0,0
14363,39875,15.000000,1.0,146.0,2019.0,White,5.0,7.0,Automatic,1997.0,...,0,0,1,0,1,0,0,0,1,0
14364,39700,10.000000,1.0,147.0,2019.0,Grey,5.0,7.0,Automatic,1997.0,...,0,0,1,0,1,0,0,0,1,0

### Body_Color

In [7]:
one_hot = pd.get_dummies(df, columns = ['body_color'])
df = one_hot
df

,price,km,prev_owner,hp,first_registration,nr_of_doors,nr_of_seats,gearing_type,displacement,cylinders,...,body_color_Brown,body_color_Gold,body_color_Green,body_color_Grey,body_color_Orange,body_color_Red,body_color_Silver,body_color_Violet,body_color_White,body_color_Yellow
0,15770,56013.000000,2.0,66.0,2016.0,5.0,5.0,Automatic,1422.0,3.0,...,0,0,0,0,0,0,0,0,0,0
1,14500,80000.000000,1.0,141.0,2017.0,3.0,4.0,Automatic,1798.0,4.0,...,0,0,0,0,0,1,0,0,0,0
2,14640,83450.000000,1.0,85.0,2016.0,4.0,4.0,Automatic,1598.0,4.0,...,0,0,0,0,0,0,0,0,0,0
3,14500,73000.000000,1.0,66.0,2016.0,3.0,4.0,Automatic,1422.0,3.0,...,1,0,0,0,0,0,0,0,0,0
4,16790,16200.000000,1.0,66.0,2016.0,5.0,5.0,Automatic,1422.0,3.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14360,39980,100.000000,1.0,118.0,2019.0,5.0,7.0,Automatic,1598.0,4.0,...,0,0,0,0,0,0,0,0,1,0
14361,39950,34130.127828,1.0,147.0,2019.0,5.0,5.0,Automatic,1997.0,4.0,...,0,0,0,0,0,0,0,0,0,0
14362,39950,34130.127828,1.0,147.0,2019.0,5.0,5.0,Automatic,1997.0,4.0,...,0,0,0,1,0,0,0,0,0,0
14363,39875,15.000000,1.0,146.0,2019.0,5.0,7.0,Automatic,1997.0,4.0,...,0,0,0,0,0,0,0,0,1,0
14364,39700,10.000000,1.0,147.0,2019.0,5.0,7.0,Automatic,1997.0,4.0,...,0,0,0,1,0,0,0,0,0,0

### Gearing Type

In [8]:
one_hot = pd.get_dummies(df, columns = ['gearing_type'])
df = one_hot
df

,price,km,prev_owner,hp,first_registration,nr_of_doors,nr_of_seats,displacement,cylinders,fuel,...,body_color_Grey,body_color_Orange,body_color_Red,body_color_Silver,body_color_Violet,body_color_White,body_color_Yellow,gearing_type_Automatic,gearing_type_Manual,gearing_type_Semi-automatic
0,15770,56013.000000,2.0,66.0,2016.0,5.0,5.0,1422.0,3.0,Diesel,...,0,0,0,0,0,0,0,1,0,0
1,14500,80000.000000,1.0,141.0,2017.0,3.0,4.0,1798.0,4.0,Benzine,...,0,0,1,0,0,0,0,1,0,0
2,14640,83450.000000,1.0,85.0,2016.0,4.0,4.0,1598.0,4.0,Diesel,...,0,0,0,0,0,0,0,1,0,0
3,14500,73000.000000,1.0,66.0,2016.0,3.0,4.0,1422.0,3.0,Diesel,...,0,0,0,0,0,0,0,1,0,0
4,16790,16200.000000,1.0,66.0,2016.0,5.0,5.0,1422.0,3.0,Diesel,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14360,39980,100.000000,1.0,118.0,2019.0,5.0,7.0,1598.0,4.0,Diesel,...,0,0,0,0,0,1,0,1,0,0
14361,39950,34130.127828,1.0,147.0,2019.0,5.0,5.0,1997.0,4.0,Diesel,...,0,0,0,0,0,0,0,1,0,0
14362,39950,34130.127828,1.0,147.0,2019.0,5.0,5.0,1997.0,4.0,Diesel,...,1,0,0,0,0,0,0,1,0,0
14363,39875,15.000000,1.0,146.0,2019.0,5.0,7.0,1997.0,4.0,Diesel,...,0,0,0,0,0,1,0,1,0,0
14364,39700,10.000000,1.0,147.0,2019.0,5.0,7.0,1997.0,4.0,Diesel,...,1,0,0,0,0,0,0,1,0,0

### Fuel

In [9]:
one_hot = pd.get_dummies(df, columns = ['fuel'])
df = one_hot
df

,price,km,prev_owner,hp,first_registration,nr_of_doors,nr_of_seats,displacement,cylinders,co_2_emission,...,body_color_Violet,body_color_White,body_color_Yellow,gearing_type_Automatic,gearing_type_Manual,gearing_type_Semi-automatic,fuel_Benzine,fuel_Diesel,fuel_Hybrid,fuel_LPG/CNG
0,15770,56013.000000,2.0,66.0,2016.0,5.0,5.0,1422.0,3.0,992.0,...,0,0,0,1,0,0,0,1,0,0
1,14500,80000.000000,1.0,141.0,2017.0,3.0,4.0,1798.0,4.0,1292.0,...,0,0,0,1,0,0,1,0,0,0
2,14640,83450.000000,1.0,85.0,2016.0,4.0,4.0,1598.0,4.0,992.0,...,0,0,0,1,0,0,0,1,0,0
3,14500,73000.000000,1.0,66.0,2016.0,3.0,4.0,1422.0,3.0,992.0,...,0,0,0,1,0,0,0,1,0,0
4,16790,16200.000000,1.0,66.0,2016.0,5.0,5.0,1422.0,3.0,1092.0,...,0,0,0,1,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14360,39980,100.000000,1.0,118.0,2019.0,5.0,7.0,1598.0,4.0,1232.0,...,0,1,0,1,0,0,0,1,0,0
14361,39950,34130.127828,1.0,147.0,2019.0,5.0,5.0,1997.0,4.0,1392.0,...,0,0,0,1,0,0,0,1,0,0
14362,39950,34130.127828,1.0,147.0,2019.0,5.0,5.0,1997.0,4.0,1392.0,...,0,0,0,1,0,0,0,1,0,0
14363,39875,15.000000,1.0,146.0,2019.0,5.0,7.0,1997.0,4.0,1392.0,...,0,1,0,1,0,0,0,1,0,0
14364,39700,10.000000,1.0,147.0,2019.0,5.0,7.0,1997.0,4.0,1392.0,...,0,0,0,1,0,0,0,1,0,0

### Extras

In [10]:
one_hot = pd.get_dummies(df, columns = ['extras'])
df = one_hot
df

,price,km,prev_owner,hp,first_registration,nr_of_doors,nr_of_seats,displacement,cylinders,co_2_emission,...,body_color_White,body_color_Yellow,gearing_type_Automatic,gearing_type_Manual,gearing_type_Semi-automatic,fuel_Benzine,fuel_Diesel,fuel_Hybrid,fuel_LPG/CNG,extras_Alloy wheels
0,15770,56013.000000,2.0,66.0,2016.0,5.0,5.0,1422.0,3.0,992.0,...,0,0,1,0,0,0,1,0,0,1
1,14500,80000.000000,1.0,141.0,2017.0,3.0,4.0,1798.0,4.0,1292.0,...,0,0,1,0,0,1,0,0,0,1
2,14640,83450.000000,1.0,85.0,2016.0,4.0,4.0,1598.0,4.0,992.0,...,0,0,1,0,0,0,1,0,0,1
3,14500,73000.000000,1.0,66.0,2016.0,3.0,4.0,1422.0,3.0,992.0,...,0,0,1,0,0,0,1,0,0,1
4,16790,16200.000000,1.0,66.0,2016.0,5.0,5.0,1422.0,3.0,1092.0,...,0,0,1,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14360,39980,100.000000,1.0,118.0,2019.0,5.0,7.0,1598.0,4.0,1232.0,...,1,0,1,0,0,0,1,0,0,1
14361,39950,34130.127828,1.0,147.0,2019.0,5.0,5.0,1997.0,4.0,1392.0,...,0,0,1,0,0,0,1,0,0,1
14362,39950,34130.127828,1.0,147.0,2019.0,5.0,5.0,1997.0,4.0,1392.0,...,0,0,1,0,0,0,1,0,0,1
14363,39875,15.000000,1.0,146.0,2019.0,5.0,7.0,1997.0,4.0,1392.0,...,1,0,1,0,0,0,1,0,0,1
14364,39700,10.000000,1.0,147.0,2019.0,5.0,7.0,1997.0,4.0,1392.0,...,0,0,1,0,0,0,1,0,0,1

In [ ]:
df = pd.get_dummies(df)
df.sample(50)

In [18]:
df.to_csv("Capstone_project_finalstep_Ahmet", encoding='utf-8', index=False)

In [ ]:
filter()